# This file was generated by GoReleaser. DO NOT EDIT.
cask "control" do
  name "control"
  desc "Generate SVG diagrams from plain text"
  homepage "https://github.com/StephanSchmidt/control"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "control"

  on_macos do
    on_intel do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_darwin_amd64.tar.gz"
      sha256 "c55eff15760082f9f38637acc0c4daa5aed731f4fe2bd0c6c5bab6e1806615e7"
    end
    on_arm do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_darwin_arm64.tar.gz"
      sha256 "e547a445a39e2f5040e27f9bcaf12711a88622955198aa08931dd54f1fc9534c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_linux_amd64.tar.gz"
      sha256 "2f9611d248ea16954e6e61206ed54fab7983861ce3d2f2834353d4c9d6ff055e"
    end
    on_arm do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_linux_arm64.tar.gz"
      sha256 "697ac24adbbf0f8e4b43189ae249aa10bd2e6964a0b95801e6e2e8a9d0970d89"
    end
  end

  # No zap stanza required
end
