# This file was generated by GoReleaser. DO NOT EDIT.
cask "control" do
  name "control"
  desc "Generate SVG diagrams from plain text"
  homepage "https://github.com/StephanSchmidt/control"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "control"

  on_macos do
    on_intel do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_darwin_amd64.tar.gz"
      sha256 "0197c13e91cdaba323ca23b54712087c579d58cb58fb1838460406c696b6d0f8"
    end
    on_arm do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_darwin_arm64.tar.gz"
      sha256 "4bbac5debeb2ffd5bf86fd51a875e7e49e6ce9839fa0702ef177a5d8bf269f0c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_linux_amd64.tar.gz"
      sha256 "9b81190f377acacd93b6b33b720e6e8cbb7f215f9f3f2cbeb111c559171e745d"
    end
    on_arm do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_linux_arm64.tar.gz"
      sha256 "60dcbff784511cdbccc713a059030ccf33b79ef3a03310fbb78d092da62eb2fc"
    end
  end

  # No zap stanza required
end
