# This file was generated by GoReleaser. DO NOT EDIT.
cask "control" do
  name "control"
  desc "Generate SVG diagrams from plain text"
  homepage "https://github.com/StephanSchmidt/control"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "control"

  on_macos do
    on_intel do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_darwin_amd64.tar.gz"
      sha256 "658959f78f92ca328fe3926aa8a82b1e3cceb9fef87960067a32493e99ece1a6"
    end
    on_arm do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_darwin_arm64.tar.gz"
      sha256 "6959fd1934e446119fc418b6e8434b574dac46124071db6b806f25c719167510"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_linux_amd64.tar.gz"
      sha256 "5ae8fa34cc6e518b54f4ff9f981d5f2543d50a8092dcd25334225a886dd83754"
    end
    on_arm do
      url "https://github.com/StephanSchmidt/control/releases/download/v#{version}/control_#{version}_linux_arm64.tar.gz"
      sha256 "9bd4e218a7c2dd3ba7e2ef25ed533278571c7c781f988a8c5cc71451df259187"
    end
  end

  # No zap stanza required
end
